---
- name: ensure polybar build dir exists
  file:
    path: "{{ polybar_install_path }}{{ archive_dir.files[0] }}build"
    state: directory
  register: build_dir
  become: true

- name: cmake polybar
  command: cmake ..
  args:
    chdir: "{{ build_dir.path }}"
  become: true

# - name: make install polybar
#   make:
#     chdir: "{{ build_dir.path }}"
#     target: install
#   become: true

- name: make install polybar with checkinstall
  command: checkinstall --pkgname=polybar --pkgversion="{{ polybar.json.tag_name }}" --pkgsource="{{ build_dir.path }}" -y
  args:
    chdir: "{{ build_dir.path }}"
  become: true
